### ISSUE TITLE
ImportError: cannot import name AppConf

### ISSUE THREAD

**Issue by ATpiu** [RASSec/A_Scan_Framework#1]
when l execute “python manage.py celery worker -c 40”,an error happened:
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/python27/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/python27/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/local/python27/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/python27/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/local/python27/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/python27/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/A_Scan_Framework/users/models.py", line 9, in <module>
    from .conf import settings
  File "/home/A_Scan_Framework/users/conf.py", line 1, in <module>
    from appconf import AppConf
ImportError: cannot import name AppConf

Unluckily,l tried appconf v0.1.1 to v0.1.10,but all failed and the error is the same.
My python is 2.7.12
Do let me know if further information is required.
Thx.

**Comment by RASSec** [comment]
you can use pyton 3.4

2018-07-16 

exp_data 



发件人：ATpiu <notifications@github.com>
发送时间：2018-07-14 17:42
主题：[RASSec/A_Scan_Framework] ImportError: cannot import name AppConf (#1)
收件人："RASSec/A_Scan_Framework"<A_Scan_Framework@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

when l execute “python manage.py celery worker -c 40”,an error happened:
Traceback (most recent call last):
File "manage.py", line 15, in 
execute_from_command_line(sys.argv)
File "/usr/local/python27/lib/python2.7/site-packages/django/core/management/init.py", line 364, in execute_from_command_line
utility.execute()
File "/usr/local/python27/lib/python2.7/site-packages/django/core/management/init.py", line 338, in execute
django.setup()
File "/usr/local/python27/lib/python2.7/site-packages/django/init.py", line 27, in setup
apps.populate(settings.INSTALLED_APPS)
File "/usr/local/python27/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
app_config.import_models()
File "/usr/local/python27/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
self.models_module = import_module(models_module_name)
File "/usr/local/python27/lib/python2.7/importlib/init.py", line 37, in import_module
import(name)
File "/home/A_Scan_Framework/users/models.py", line 9, in 
from .conf import settings
File "/home/A_Scan_Framework/users/conf.py", line 1, in 
from appconf import AppConf
ImportError: cannot import name AppConf
Unluckily,l tried appconf v0.1.0 to v0.1.10,but all failed and the error is the same.
My python is 2.7.12
Do let me know if further information is required.
Thx.
